# Generated by Django 2.2 on 2019-04-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('g', 'grado'), ('p', 'postgrado'), ('d', 'doctorado')], max_length=1)),
                ('nombre_programa', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisito', models.TextField(blank=True, null=True)),
                ('duracion', models.CharField(max_length=50)),
                ('contactos', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
