# Generated by Django 2.2 on 2019-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becas',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
